# Strong password generated by Terraform; nobody has to choose or type it
resource "random_password" "db" {
  length           = 24
  special          = true
  override_special = "-_"
  min_upper        = 2
  min_lower        = 2
  min_numeric      = 2
  min_special      = 2
}

# Managed PostgreSQL server
resource "azurerm_postgresql_flexible_server" "db" {
  name                          = "psql-assetreg-${random_string.suffix.result}"
  resource_group_name           = azurerm_resource_group.app.name
  location                      = azurerm_resource_group.app.location
  version                       = "16"
  sku_name                      = "B_Standard_B1ms"
  storage_mb                    = 32768
  backup_retention_days         = 7
  administrator_login           = var.db_admin_username
  administrator_password        = random_password.db.result
  public_network_access_enabled = true
  tags                          = var.tags

  # Azure chooses the availability zone; don't treat that as a change
  lifecycle {
    ignore_changes = [zone]
  }
}

# The application's database on that server
resource "azurerm_postgresql_flexible_server_database" "assets" {
  name      = var.db_name
  server_id = azurerm_postgresql_flexible_server.db.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}

# Allow connections from Azure services, such as Container Apps
resource "azurerm_postgresql_flexible_server_firewall_rule" "azure_services" {
  name             = "AllowAzureServices"
  server_id        = azurerm_postgresql_flexible_server.db.id
  start_ip_address = "0.0.0.0"
  end_ip_address   = "0.0.0.0"
}